<Project>
  <PropertyGroup>
    <AppVersion>5.0.0</AppVersion>
    <AppBuildNumber>19</AppBuildNumber>
    <Version>$(AppVersion)</Version>
    <PackageVersion>$(AppVersion)</PackageVersion>
    <ApplicationDisplayVersion>$(AppVersion)</ApplicationDisplayVersion>
    <ApplicationVersion>50$(AppBuildNumber)</ApplicationVersion>
    <AppxPackageVersion>$(AppVersion).0</AppxPackageVersion>
  </PropertyGroup>
</Project>
