<Project>
  <PropertyGroup>
    <AppVersion>5.6.0</AppVersion>
    <AppBuildNumber>44</AppBuildNumber>
    <Version>$(AppVersion)</Version>
    <PackageVersion>$(AppVersion)</PackageVersion>
    <ApplicationDisplayVersion>$(AppVersion)</ApplicationDisplayVersion>
    <ApplicationVersion>50$(AppBuildNumber)</ApplicationVersion>
    <AppxPackageVersion>$(AppVersion).0</AppxPackageVersion>
  </PropertyGroup>
</Project>
