<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon>Resources\appicon.ico</ApplicationIcon>
		<AssemblyName>Obxodka</AssemblyName>
		<AssemblyVersion>1.0.2</AssemblyVersion>
		<FileVersion>1.0.2</FileVersion>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Engine\obxodka-engine.exe">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3719.77" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Resources\appicon.ico" />
		<Resource Include="Resources\appicon.png" />
		<Resource Include="Resources\back_arrow.png" />
		<Resource Include="Resources\email_icon.png" />
		<Resource Include="Resources\eye_icon.png" />
		<Resource Include="Resources\eye_off.png" />
		<Resource Include="Resources\lock_icon.png" />
		<Resource Include="Resources\plus_icon.png" />
		<Resource Include="Resources\user_icon.png" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
	</ItemGroup>

</Project>