//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("android29.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("windows10.0.19041.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("linux")]
[assembly: System.Reflection.AssemblyCompanyAttribute("obxodka.Client.Tests")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("4.8.6.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("4.8.6+bb914eb3b03ad363c0ef1c68fb02e7549cbe16b3")]
[assembly: System.Reflection.AssemblyProductAttribute("obxodka.Client.Tests")]
[assembly: System.Reflection.AssemblyTitleAttribute("obxodka.Client.Tests")]
[assembly: System.Reflection.AssemblyVersionAttribute("4.8.6.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows10.0.19041.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows10.0.19041.0")]

// Generated by the MSBuild WriteCodeFragment class.

