<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Configurations>Debug;Release;Debug_EXE;Release_EXE</Configurations>
    <TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">net10.0;net10.0-android;net10.0-windows10.0.19041.0</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('linux'))">net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="obxodka.Core.Protos" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\security.proto" GrpcServices="Both" Access="Public" />
  </ItemGroup>

<ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.80.0" />
    <PackageReference Include="Google.Protobuf" Version="3.35.1" />
    <PackageReference Include="Grpc.Tools" Version="2.81.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
</ItemGroup>

<ItemGroup>
  <ProjectReference Include="..\obxodka.Shared\obxodka.Shared.csproj" />
</ItemGroup>

</Project>