<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Configurations>Debug;Release;Debug_EXE;Release_EXE</Configurations>
    <TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">net10.0;net10.0-android;net10.0-windows10.0.19041.0</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('linux'))">net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CA1716</NoWarn>
  </PropertyGroup>

</Project>
