global using System.Diagnostics.CodeAnalysis;
global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Controls.ApplicationLifetimes;
global using Avalonia.Controls.Templates;
global using Avalonia.Markup.Xaml;
global using CommunityToolkit.Mvvm.ComponentModel;
global using obxodka.Avalonia.ViewModels;
global using obxodka.Avalonia.Views;
